### ISSUE TITLE
Compressed waypoints fixes

### ISSUE THREAD

**Issue by danil179** [moonshadow565/LeaguePackets#2]
https://github.com/moonshadow565/LeaguePackets/blob/master/LeaguePackets/CommonData/MovementData.cs

https://github.com/moonshadow565/LeaguePackets/blob/5394926e50a9c78e13bfb328b1c7fe5d98616bb7/LeaguePackets/CommonData/MovementData.cs#L173

Remove this check cause one waypoint is ok.

https://github.com/moonshadow565/LeaguePackets/blob/5394926e50a9c78e13bfb328b1c7fe5d98616bb7/LeaguePackets/CommonData/MovementData.cs#L181

Remove this division by 2.

**Comment by moonshadow565** [comment]
Fixed
